system: You are an AI assistant knowledgeable about {{domain}} domain. Be accurate but concise in response.

introduction: | 
  Please break down the following snippet from an article about {{domain}} into atomic facts.

principles: |
  1. Make sure each fact is grounded in the given text.
  2. Include any necessary information needed to explain the fact or concept
  3. The atomic facts should be as simple as possible, if it’s compound sentence, break down one more time
  4. For clarity, avoid using pronouns like ’it’, ’he’, ’she’, ’this’, ’that’ etc., and instead use the full names or titles.
  5. Focus only on key concepts and facts. Skip any question or problems mentioned in the passage.

examples: |
  To help you understand the task, here is an example:
  [Passage]
  The tournament was contested by ten national teams, maintaining the same format used in 2019. After six weeks of round-robin matches, India, South Africa, Australia, and New Zealand finished as the top four and qualified for the knockout stage. In the knockout stage, India and Australia beat New Zealand and South Africa, respectively, to advance to the final, played on 19 November at the Narendra Modi Stadium in Ahmedabad. Australia won the final by six wickets, winning their sixth Cricket World Cup title.
  [Facts]
  1. The tournament was contested by ten national teams.
  2. The tournament maintained the same format used in 2019.
  3. The round-robin matches lasted for six weeks.
  4. India finished as one of the top four teams.
  5. South Africa finished as one of the top four teams.
  6. Australia finished as one of the top four teams.
  7. New Zealand finished as one of the top four teams.
  8. India, South Africa, Australia, and New Zealand qualified for the knockout stage.
  9. In the knockout stage, India beat New Zealand.
  10. In the knockout stage, Australia beat South Africa.
  11. India advanced to the final.
  12. Australia advanced to the final.
  13. The final was played on 19 November.
  14. The final was held at the Narendra Modi Stadium in Ahmedabad.
  15. Australia won the final by six wickets.
  16. Australia won their sixth Cricket World Cup title.
  [End]


generation: |
  Now it's your turn breakdown following snippet from article about {{domain}} into atomic facts following similar style as above examples
  [Passage]
  {{document}}
  [Facts]


start_tags: [""]
end_tags: [""]